### ISSUE TITLE
KeyError while finding uuid

### ISSUE THREAD

**Issue by eivindjahren** [equinor/fmu-sumo-sim2sumo#85]
Error while running SIM2SUMO

```
Cannot open file, will return empty dict
Traceback (most recent call last):
File ".../bin/sim2sumo", line 8, in <module>
sys.exit(main())
File ".../lib64/python3.8/site-packages/fmu/sumo/sim2sumo/main.py", line 84, in main
dispatcher = Dispatcher(one_datafile, args.env)
File ".../lib64/python3.8/site-packages/fmu/sumo/sim2sumo/common.py", line 337, in __init__
self._parentid = get_case_uuid(datafile)
File ".../lib64/python3.8/site-packages/fmu/sumo/sim2sumo/common.py", line 58, in get_case_uuid
uuid = case_meta["fmu"]["case"]["uuid"]
KeyError: 'fmu'
```

**Comment by equinor-ruaj** [comment]
`Cannot open file, will return empty dict` is from `yaml_load()` not able to open the config file.
Could they have a setup where the config files are not where expected @daniel-sol ?

**Comment by equinor-ruaj** [comment]
#84 added handling for when Dispatcher init fails.
