### ISSUE TITLE
local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by berland** [equinor/fmu-sumo-sim2sumo#89]
sumo_upload fails on bleeding builds:

https://github.com/equinor/komodo-releases/actions/runs/10811849462/job/29995941206

```
The script 'SumoUpload' caused an error while running:
local variable 'e' referenced before assignment
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-20240911-1241-py38-rhel8/root/lib64/python3.8/site-packages/fmu/sumo/uploader/scripts/sumo_upload.py", line 133, in sumo_upload_main
    e = uploader.CaseOnDisk(
TypeError: __init__() takes from 3 to 5 positional arguments but 7 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-20240911-1241-py38-rhel8/root/lib64/python3.8/site-packages/ert/config/ert_script.py", line 1[45](https://github.com/equinor/komodo-releases/actions/runs/10811849462/job/29995941206#step:5:46), in initializeAndRun
    return self.run(*arguments)
  File "/prog/res/komodo/bleeding-20240911-1241-py38-rhel8/root/lib64/python3.8/site-packages/fmu/sumo/uploader/scripts/sumo_upload.py", line 186, in run
    sumo_upload_main(
  File "/prog/res/komodo/bleeding-20240911-1241-py38-rhel8/root/lib64/python3.8/site-packages/fmu/sumo/uploader/scripts/sumo_upload.py", line 164, in sumo_upload_main
    extra={"objectUuid": e.fmu_case_uuid},
UnboundLocalError: local variable 'e' referenced before assignment
Number of active realizations (0) is less than the specified MIN_REALIZATIONS(1)
Workflow job SUMO_UPLOAD failed
Realization: 0 failed after reaching max submit (1):
	
job SUMO_UPLOAD failed with: 'Process exited with status code 2'
	stderr file: '/tmp/f_scout_ci/actions-runner-01/_temp/fmu-drogon/ert/model/scratch/f_scout_ci/01_drogon_design/realization-0/iter-0/sumo_upload.stderr.96',
	its contents:
usage: sumo_upload [-h] [--config_path CONFIG_PATH] [--sumo_mode SUMO_MODE]
                   [--threads THREADS] [--metadata_path METADATA_PATH] [-v]
                   [--debug]
                   casepath searchpath env
sumo_upload: error: unrecognized arguments: --parameter_path parameters.txt
```

**Comment by equinor-ruaj** [comment]
https://github.com/equinor/fmu-sumo-uploader/pull/86 and https://github.com/equinor/fmu-sumo-uploader/pull/88 should have resolved this issue.
